/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DealResType {
    #[serde(rename = "Contact")]
    Contact,

}

impl ToString for DealResType {
    fn to_string(&self) -> String {
        match self {
            Self::Contact => String::from("Contact"),
        }
    }
}

impl Default for DealResType {
    fn default() -> DealResType {
        Self::Contact
    }
}

