/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DealResourceOneOf {
    #[serde(rename = "Contact")]
    pub contact: Box<models::DealContact>,
}

impl DealResourceOneOf {
    pub fn new(contact: models::DealContact) -> DealResourceOneOf {
        DealResourceOneOf {
            contact: Box::new(contact),
        }
    }
}

