/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DealResource {
    DealResourceOneOf(Box<models::DealResourceOneOf>),
}

impl Default for DealResource {
    fn default() -> Self {
        Self::DealResourceOneOf(Default::default())
    }
}

