/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DealResourceListWithPagination {
    #[serde(rename = "data")]
    pub data: Box<models::DealResourceList>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl DealResourceListWithPagination {
    pub fn new(data: models::DealResourceList, total: i64) -> DealResourceListWithPagination {
        DealResourceListWithPagination {
            data: Box::new(data),
            total,
        }
    }
}

