/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDealByOrgRespBody {
    #[serde(rename = "deals")]
    pub deals: Vec<models::Deal>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl ListDealByOrgRespBody {
    pub fn new(deals: Vec<models::Deal>, total: i64) -> ListDealByOrgRespBody {
        ListDealByOrgRespBody {
            deals,
            total,
        }
    }
}

